# Generated by Django 4.2.2 on 2023-06-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seaanimal',
            options={'ordering': ['name']},
        ),
    ]
