# Generated by Django 4.2.2 on 2023-06-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_seaanimal_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cephalopod',
            old_name='animal',
            new_name='species',
        ),
        migrations.AddField(
            model_name='seaanimal',
            name='image',
            field=models.CharField(default='', max_length=250),
        ),
    ]
