# Generated by Django 4.2.2 on 2023-06-29 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_animal_cephalopod_species_seaanimal_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeaAnimal',
            new_name='Species',
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=500)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal', to='main_app.species')),
            ],
        ),
    ]
